<?php

namespace AppBundle\Repository;

/**
 * BlogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogsRepository extends \Doctrine\ORM\EntityRepository
{
}
